Repository CMS-Enterprise/sbom-harbor-ui, pull requests merged in 2023-07, with the labels that each got.

#108 build: remove testing-library/react-hooks dev dependency
  package.json
  src/actions/logoutUser.test.tsx
  yarn.lock
Labels: dependencies

#109 test(hooks/useFetch): add coverage
  src/hooks/useFetch.test.ts
  src/hooks/useFetch.ts
Labels: test

#110 refactor(utils/sanitizeUrl): support all protocols in url
  src/errors/AuthError.test.ts
  src/errors/AuthError.ts
  src/utils/getJWT.test.ts
  src/utils/getJWT.ts
  src/utils/sanitizeUrl.test.ts
  src/utils/sanitizeUrl.ts
Labels: refactor

#111 chore: add issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/general-issue.md
  .github/ISSUE_TEMPLATE/propose-an-idea.md
Labels: documentation

#116 chore(types): add util types, add type docs
  declaration.d.ts
Labels: documentation

#113 build: remove redundant icons dependency md-material-ui
  package.json
  src/components/SocialLoginButtons.tsx
  src/views/Dashboard/Team/components/TeamMembersTable.tsx
  src/views/Dashboard/Team/components/TeamViewProjectCard.tsx
  src/views/Dashboard/Team/components/TeamViewProjectCreateCard.tsx
  src/views/Dashboard/Team/components/TeamViewProjectCreationCard.tsx
  src/views/SignIn/SignIn.tsx
  yarn.lock
Labels: dependencies, refactor
